name: HH Uzbekistan -> Telegram

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

concurrency:
  group: hh-uz-telegram
  cancel-in-progress: true

permissions:
  contents: write


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Run
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          HH_USER_AGENT: ${{ secrets.HH_USER_AGENT }}
          HH_HOST: "hh.uz"
          MAX_POSTS: "10"
          SLEEP_BETWEEN_POSTS: "2"
        run: python hh_to_telegram.py

      - name: Commit state
        run: |
          if [ -f state.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            git add state.json
            git diff --cached --quiet && exit 0

            git commit -m "Update state"

            # Remote dagi yangiliklarni olib, ustiga qo'yib push qiladi
            git pull --rebase origin main

            # Push (agar yana urilsa, 2 marta urinib ko'radi)
            git push origin main || (sleep 3 && git pull --rebase origin main && git push origin main)
          fi
